language: python
python: "3.7"
install:
- pip install pipenv
- pipenv install --dev
script:
- make lint
deploy:
  provider: heroku
  app: randommap
  api_key:
    secure: gFS2nbpq9CyDV+ls1Eb7XrvXVzt4lrVAxNEb1sgxva5zdWiPxZ/Lng8aWNeG97CvSTTO5MiVEo6V6RRy6+rXGN4e0p58N+7La289dc7v27qVnqjlyduPvf8D82G9dVzTii9y7XL8+SB7ibZOR0qL3mz4ogGbi82lj/sisrrQC0BGXoj/SHXXz1kt6wcz05JynJuVbSWmr3AyKnoBP4bLAkkNPk3x28/PeqS4w/qxIpXwxg7JhqkYMF7E5nptzMXjezEynSHqowE0mxhivPw5V6IqphHFopsNxWOa1XH6n+wz5xzXDAF7suLEXr6HBuX+upZFJK1MvS0HPE7RRZt+FhVoTKP5xEpC68ltP6VrSFjtrTYECPuiy/dVPBgk3mMW0J+RaZrQVskWboKbTZdi0+YHhAEvKEq06hErsFPt/J1VS5tCaw38kcYVs9wlnRCIEPPfBYnUUX8jjE7b+llVpW7K0hrT4zJud+NylYRLj6ppLu0lE4BaPl7h1lYqqDRuPi8mH5SCRxCeIV+V784I+b9Eukj2+jltbyTIByOs9dBq0TVqAUb+NA6jl0kp7PrnSUo9i5HQRlqw7q0J2jyLFVo70DRpDSpDJwR/T096XX8Ewi3zJrd17OScMUZwh5sP5Ef4yb2VhPWKU6CWfegRfCVFIYFERUDmFrwuuOpLU/c=
