version: '2'

services:
  app:
    build:
      context: ./app
    depends_on:
      - redis
    volumes:
      - ./app:/app
    environment:
      - REDIS_HOST=redis
    env_file: app.env
    ports:
      - "5000:5000"

  redis:
    image: redis:3.2-alpine
