version: '2'

services:
  app:
    build:
      context: ./randommap_website
    depends_on:
      - redis
    volumes:
      - ./randommap_website:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_PORT=${FLASK_PORT}
    env_file: app.env
    ports:
      - "${FLASK_PORT}:5000"

  redis:
    image: redis:3.2-alpine
